development:
  key   : 'AKIAJLFBBEDDLZFLJ4DA'
  secret: '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'
  bucket: 'vtagovideos'
  folder: 'test'

test:

production:
  key   : 'AKIAJLFBBEDDLZFLJ4DA'
  secret: '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'
  bucket: 'vtagovideos'
  folder: 'videos'
