development:
  key   : 'AKIAJLFBBEDDLZFLJ4DA'
  secret: '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'
  bucket: 'vtago_videos'

test:

production:
  key   : 'AKIAJLFBBEDDLZFLJ4DA'
  secret: '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'
  bucket: 'vtago_videos'
