--- 
- !ruby/object:Rubber::Configuration::InstanceItem 
  domain: vtago.com
  external_host: ec2-184-72-155-114.compute-1.amazonaws.com
  external_ip: 184.72.155.114
  image_id: ami-3e02f257
  image_type: t1.micro
  instance_id: i-ea9a6993
  internal_host: ip-10-242-51-104.ec2.internal
  internal_ip: 10.242.51.104
  name: staging
  platform: linux
  roles: 
  - !ruby/object:Rubber::Configuration::RoleItem 
    name: web
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: haproxy
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: app
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: passenger
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: apache
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: db
    options: 
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem 
    name: mysql_master
    options: {}

  root_device_type: ebs
  security_groups: 
  - vtago_staging_default
  - vtago_staging_web
  - vtago_staging_staging
  - vtago_staging_haproxy
  - vtago_staging_app
  - vtago_staging_passenger
  - vtago_staging_apache
  - vtago_staging_db
  - vtago_staging_mysql_master
  zone: us-east-1d
- volumes: {}

  static_ips: {}

