--- 
- !ruby/object:Rubber::Configuration::InstanceItem 
  domain: vtago.com
  external_host: ec2-184-73-51-0.compute-1.amazonaws.com
  external_ip: 184.73.51.0
  image_id: ami-7000f019
  image_type: m1.small
  instance_id: i-5cfac038
  internal_host: domU-12-31-39-05-15-67.compute-1.internal
  internal_ip: 10.241.22.149
  name: production
  platform: linux
  roles: 
  - !ruby/object:Rubber::Configuration::RoleItem 
    name: web
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: haproxy
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: app
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: passenger
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: apache
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: db
    options: 
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem 
    name: mysql_master
    options: {}

  root_device_type: instance-store
  security_groups: 
  - vtago_production_default
  - vtago_production_web
  - vtago_production_production
  - vtago_production_haproxy
  - vtago_production_app
  - vtago_production_passenger
  - vtago_production_apache
  - vtago_production_db
  - vtago_production_mysql_master
  zone: us-east-1c
- !ruby/object:Rubber::Configuration::InstanceItem 
  domain: vtago.com
  external_host: ec2-50-16-20-139.compute-1.amazonaws.com
  external_ip: 50.16.20.139
  image_id: ami-7000f019
  image_type: m1.small
  instance_id: i-e562c882
  internal_host: domU-12-31-39-0C-56-65.compute-1.internal
  internal_ip: 10.215.85.143
  name: detect01
  platform: linux
  roles: 
  - !ruby/object:Rubber::Configuration::RoleItem 
    name: web
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: haproxy
    options: {}

  root_device_type: instance-store
  security_groups: 
  - vtago_production_default
  - vtago_production_web
  - vtago_production_detect01
  - vtago_production_haproxy
  zone: us-east-1c
- !ruby/object:Rubber::Configuration::InstanceItem 
  domain: vtago.com
  external_host: ec2-75-101-248-75.compute-1.amazonaws.com
  external_ip: 75.101.248.75
  image_id: ami-7000f019
  image_type: m1.small
  instance_id: i-cb49e3ac
  internal_host: ip-10-190-125-48.ec2.internal
  internal_ip: 10.190.125.48
  name: fbupload01
  platform: linux
  roles: 
  - !ruby/object:Rubber::Configuration::RoleItem 
    name: web
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: haproxy
    options: {}

  root_device_type: instance-store
  security_groups: 
  - vtago_production_default
  - vtago_production_web
  - vtago_production_fbupload01
  - vtago_production_haproxy
  zone: us-east-1c
- volumes: {}

  static_ips: {}

